name: Scream 3 Music
url: /

menu:
  Home: /
  About: /about/
  Archives: /archives/
  Hair: /categories/hair/
  Skincare: /categories/skincare/
  Culture: /categories/culture/
  Makeup: /categories/makeup/
  Wellness: /categories/wellness/

favicon: /images/favicon.png
logo: /images/logo.jpg

# Disqus shortname
disqus:

# Analytics
google_analytics:

# Copyright Infomation
copyright:
  since: 2013
  name: Scream 3 Music
  url: www.scream3music.com
